### ISSUE TITLE
Questions for Step 2

### ISSUE THREAD

**Issue by jialin-wu-02** [cloudflare-internship-2020/internship-application-fullstack#1]
For step 2:

> 2. Request a (random: see #3) variant
> Make a fetch request to one of the two URLs, and return it as the response from the script.

I am wondering what type of response should we send back? Should it just be the plain text response from one of the two URLs? (aka HTML source code)

**Comment by jialin-wu-02** [comment]
I figured it out.

> you'll deploy an application that will randomly send users to one of two webpages.

**Comment by 123lenah** [comment]
Can you explain how you figured it out? I'm still trying to figure out what type of response to send back

**Comment by jialin-wu-02** [comment]
Please do not post any code here. @kasim95
