### ISSUE TITLE
Cookies can be written but not read from a serviceWorker

### ISSUE THREAD

**Issue by joseph-mpo-yeti** [cloudflare-internship-2020/internship-application-fullstack#6]
Extra Credit 2 should be removed or updated with a possible solution because headers are stripped from the request before it gets to the serviceWorker's handler. Cookies can be set but not read from the serviceWorker. localStorage and other storage solutions are not accessible from the serviceWorker either. In conclusion, persistence is not achievable at the moment.

**Comment by zllovesuki** [comment]
Cloudflare Workers (CW) is a different type of technology than Service Worker (SW). While SW must be downloaded first on client side and requires a supported browser, CW runs on CF's edge network and it doesn't have the same constraint as SW. CW is written against the SW API.

You can read more about it here: https://blog.cloudflare.com/cloudflare-workers-unleashed/

**Comment by joseph-mpo-yeti** [comment]
You are right! Thanks for clarifying.
