### ISSUE TITLE
TypeError: Failed to execute 'fetch' on 'Window': parameter 2 ('init') is not an object.

### ISSUE THREAD

**Issue by 9916103020** [cloudflare-internship-2020/internship-application-fullstack#7]
Please can anyone tell me what this error is about and how to resolve it? I am new to Javascript so may this is a basic mistake or error.
My code showing error:
`fetch('https://cfw-takehome.developers.workers.dev/api/variants', method="no-cors").then(response => response.json()).then(json => console.log(json))
`
Error screenshot:
![error](https://user-images.githubusercontent.com/22716123/79690677-47793180-8279-11ea-9352-1374d54b7219.PNG)

Thanks:)

**Comment by zllovesuki** [comment]
```
method="no-cors"
```

That looks like a Python syntax. You want it to be an object for the second argument of `fetch()`. Please take a look at the Fetch API documentation for reference: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

**Comment by 9916103020** [comment]
@zllovesuki Thanks for the quick response I was able to resolve above error and also submitted my project:)
